apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-ruleengine-backend
  labels:
    app: mc-ruleengine-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mc-ruleengine-backend
  template:
    metadata:
      labels:
        app: mc-ruleengine-backend
    spec:
      containers:
        - name: mc-ruleengine-backend
          image: acrdemos123.azurecr.io/mc-ruleengine-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
